version: '3'
services:
  front:
    image: frontend:latest
    ports:
      - 80:80
    networks:
      - mascotas-network

  back:
    image: backend:latest
    ports:
      - 7045:7045
    networks:
      - mascotas-network
    environment:
      - BACKEND_URL=http://back:7045 

  
      
  nginx:
    image: nginx
    ports:
      - 8081:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - front
    networks:
      - tarjeta-network

networks:
  tarjeta-network:



